"""
Bonus router — AI text detection and media/deepfake detection endpoints.
"""

import json
import base64
import google.generativeai as genai
from fastapi import APIRouter, UploadFile, File, Form
from pydantic import BaseModel
from typing import Optional

from app.config import GEMINI_API_KEY, GEMINI_MODEL
from app.utils.prompts import (
    AI_DETECTION_SYSTEM_PROMPT,
    AI_DETECTION_USER_PROMPT,
    MEDIA_DETECTION_SYSTEM_PROMPT,
    MEDIA_DETECTION_USER_PROMPT,
)

# Configure Gemini
genai.configure(api_key=GEMINI_API_KEY)

router = APIRouter()


class AIDetectionRequest(BaseModel):
    """Request body for AI text detection."""
    text: str


@router.post("/detect-ai")
async def detect_ai_text(request: AIDetectionRequest):
    """
    POST /detect-ai — Detect if text was generated by AI.
    
    Accepts:
        - text: The text to analyze
        
    Returns:
        JSON with AI detection analysis, confidence, and indicators.
    """
    try:
        model = genai.GenerativeModel(
            model_name=GEMINI_MODEL,
            system_instruction=AI_DETECTION_SYSTEM_PROMPT,
            generation_config=genai.GenerationConfig(
                temperature=0.1,
                max_output_tokens=4096,
            ),
        )
        
        prompt = AI_DETECTION_USER_PROMPT.format(input_text=request.text)
        response = model.generate_content(prompt)
        
        response_text = response.text.strip()
        if response_text.startswith("```"):
            lines = response_text.split("\n")
            response_text = "\n".join(lines[1:-1])
        
        result = json.loads(response_text)
        return {"success": True, "result": result}
    
    except json.JSONDecodeError as e:
        return {
            "success": False,
            "error": f"Failed to parse AI detection response: {str(e)}",
        }
    except Exception as e:
        return {
            "success": False,
            "error": f"AI detection error: {str(e)}",
        }


@router.post("/detect-media")
async def detect_media_manipulation(
    file: UploadFile = File(...),
    description: Optional[str] = Form(None),
):
    """
    POST /detect-media — Detect manipulated/deepfake media.
    
    Accepts:
        - file: Image file to analyze (multipart upload)
        - description: Optional description of the image context
        
    Returns:
        JSON with manipulation detection analysis, confidence, and indicators.
    """
    try:
        # Read the uploaded file
        contents = await file.read()
        
        # Determine MIME type
        content_type = file.content_type or "image/jpeg"
        
        # Encode as base64 for Gemini Vision
        b64_data = base64.b64encode(contents).decode("utf-8")
        
        model = genai.GenerativeModel(
            model_name=GEMINI_MODEL,
            system_instruction=MEDIA_DETECTION_SYSTEM_PROMPT,
            generation_config=genai.GenerationConfig(
                temperature=0.1,
                max_output_tokens=4096,
            ),
        )
        
        # Build multimodal content
        prompt_parts = [
            MEDIA_DETECTION_USER_PROMPT,
            {
                "inline_data": {
                    "mime_type": content_type,
                    "data": b64_data,
                }
            },
        ]
        
        if description:
            prompt_parts.insert(0, f"Context: {description}\n\n")
        
        response = model.generate_content(prompt_parts)
        
        response_text = response.text.strip()
        if response_text.startswith("```"):
            lines = response_text.split("\n")
            response_text = "\n".join(lines[1:-1])
        
        result = json.loads(response_text)
        return {"success": True, "filename": file.filename, "result": result}
    
    except json.JSONDecodeError as e:
        return {
            "success": False,
            "error": f"Failed to parse media detection response: {str(e)}",
        }
    except Exception as e:
        return {
            "success": False,
            "error": f"Media detection error: {str(e)}",
        }
